env:
    # Cirrus Specific Vars (Do *NOT* Change)
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16
    CIRRUS_SHELL: bash

task:
  name: "Build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://github.com/abousgamer/cr/raw/main/download.sh | bash
