env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Builder"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/abousgamer/cr/main/download.sh | bash
