env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Build"
  timeout_in: 120m
  container:
      image: ghcr.io/catthehacker/ubuntu:act-18.04
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://github.com/abousgamer/cr/raw/main/download.sh | bash
